<form method="POST">
    <label for="code">Code</label>
    <input id="code" name="code" type="text"><br />

    <label for="title">Title</label>
    <input id="title" name="title" type="text"><br />

    <label for="summary">Summary</label>
    <input id="summary" name="summary" type="text"><br />

    <label for="text">Text</label>
    <textarea id="text" name="text"></textarea><br />

    <label for="date">Date</label>
    <input id="date" name="date" type="text" placeholder="YYYY-MM-DD"><br />

    <label for="views">Views</label>
    <input id="views" name="views" type="text"><br />

    <button type="submit">Add</button>
</form>
